name: Lighthouse CI
on: [push, pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://sdkisito.github.io/smartcloud-ai.github.io/
            https://sdkisito.github.io/smartcloud-ai.github.io/features
          uploadArtifacts: true
          temporaryPublicStorage: true